create table faculty
(
    id    bigint NOT NULL generated by default as identity primary key,
    color varchar(255),
    name  varchar(255)
);

create table student
(
    id         bigint NOT NULL generated by default as identity primary key,
    age        integer not null,
    name       varchar(255),
    faculty_id bigint references faculty(id)
);