create table faculty
(
    faculty_id    bigint NOT NULL generated by default as identity primary key,
    color varchar(255),
    name  varchar(255)
);

ALTER TABLE faculty ADD CONSTRAINT name_unique UNIQUE (name);

create table student
(
    student_id         bigint NOT NULL generated by default as identity primary key,
    age        integer not null,
    name       varchar(255),
    faculty_id bigint
);

ALTER TABLE student ADD FOREIGN KEY (faculty_id) REFERENCES faculty(faculty_id);

create table avatar
(
    id         bigint NOT NULL generated by default as identity primary key,
    data       oid,
    file_path  varchar(255),
    file_size  bigint NOT NULL,
    media_type varchar(255),
    student_id bigint
);

ALTER TABLE avatar ADD FOREIGN KEY (student_id) REFERENCES student(student_id);

ALTER TABLE student ADD CONSTRAINT age_constraint CHECK (age >= 16);